DROP TABLE  role IF EXISTS;
DROP TABLE  menu IF EXISTS;
DROP TABLE  vote IF EXISTS;
DROP TABLE  users IF EXISTS;
DROP TABLE restaurant IF EXISTS ;

CREATE TABLE users
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1) PRIMARY KEY,
    name     VARCHAR(255)         NOT NULL,
    email    VARCHAR(255)         NOT NULL,
    password VARCHAR(255)         NOT NULL,
    enabled  BOOLEAN DEFAULT true NOT NULL
);

CREATE UNIQUE INDEX users_unique_email_idx
    ON users (email);

CREATE TABLE role
(
    user_id INTEGER      NOT NULL,
    role    VARCHAR(255) NOT NULL,
    CONSTRAINT user_roles_constraint UNIQUE (user_id, role),
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE restaurant
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    CONSTRAINT unique_restaurant_name UNIQUE (name)
);

CREATE TABLE menu
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1) PRIMARY KEY,
    restaurant_id INTEGER              NOT NULL,
    name          VARCHAR(255)         NOT NULL,
    price         DOUBLE PRECISION     NOT NULL,
    enabled       BOOLEAN DEFAULT true NOT NULL,
    FOREIGN KEY (restaurant_id) REFERENCES restaurant (id) ON DELETE CASCADE
);

CREATE TABLE vote
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1) PRIMARY KEY,
    user_id       INTEGER NOT NULL,
    restaurant_id INTEGER NOT NULL,
    voting_date   DATE    NOT NULL,
    voting_time   TIME    NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    FOREIGN KEY (restaurant_id) REFERENCES restaurant (id) ON DELETE CASCADE,
    CONSTRAINT user_date_unique_constraint UNIQUE (user_id, voting_date)
);
